#pragma config(Motor,  port1,           LeftInner,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftTop,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftBottom,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BLDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightBottom,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RightTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BRDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightInner,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <Movement.h>

task main()
{
	while(true){
		Lift(60);
		//if(vexRT[Btn6U] == 1 && vexRT[Btn5U] == 0){
		//	Lift(60);
		//}
		//else if(vexRT[Btn6U] == 0 && vexRT[Btn5U] == 1){
		//	Lift(-60);
		//}
		//else{
		//	Lift(0);
		//}
	}
}
