#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    clawpot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  bottom,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  limit,          sensorDigitalIn)
#pragma config(Sensor, dgtl4,  ELF,            sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ERF,            sensorQuadEncoder)
#pragma config(Motor,  port1,           Lift1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Lift3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Lift5,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include <Movement.h>

void pre_auton()
{

}

task autonomous()
{

}

task usercontrol()
{
	startTask(DriveControl);
	startTask(LiftControl);

	while (1)
	{
		if (vexRT[Btn8U]) dumping();
		if (vexRT[Btn8D] && vexRT[Btn7D]) auto1();
		if (vexRT[Btn8L] && vexRT[Btn7L]) auto2();
		wait1Msec(20);
	}
}
