#pragma config(Sensor, in1,    rightclaw,      sensorPotentiometer)
#pragma config(Sensor, in2,    pot,            sensorPotentiometer)
#pragma config(Sensor, in3,    leftclaw,       sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  RightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftEnc,        sensorQuadEncoder)
#pragma config(Motor,  port1,           TRL,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ClawR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           MLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           MRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           TLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ClawL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BRL,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include <Movement.h>
#include <Auton.h>
#include <LCD.h>

void hangBlock()
{
	startTask(PotValues);
	startTask(LiftControl);
	flipout();
	liftHolding = -80;
	drive(400, 50, 0.1, 0, 0, true);
	potValues(SensorValue[pot]);
	liftHolding = -12;
	startTask(clawSync);
	clawTarget = clawClosed;
	wait1Msec(1500);
	startTask(hold);
	drive(-1000, 110, 0.1, 0, 0);
	while (abs(SensorValue[LeftEnc]) < 500) wait1Msec(20);
	startTask(dumping);
	while (dumpMode != 1) wait1Msec(20);
}

void pre_auton()
{
	startTask(selectAuton);
	fillSlew(0);
	//SensorValue[blinker] = 0;
	resetEncoders();
	gyroCalibrate();
	potValues(SensorValue[pot]);
	//SensorValue[blinker] = 1;
}


task autonomous()
{

}

task usercontrol()
{
	//hangBlock();
	stopTask(hold);
	startTask(PotValues);
	startTask(clawSync);
	clawTarget = clawOpen;
	startTask(DriveControl);
	startTask(LiftControl);
	startTask(IntakeControl);

	while (1)
	{
		if (vexRT[Btn6U])
		{
			while (vexRT[Btn6U]) wait1Msec(20);
			if (dumpMode == 1) startTask(hold);
			else startTask(dumping);
		}
		if (vexRT[Btn8R] && vexRT[Btn7R])
		{
		}
		if (vexRT[Btn7L])
		{
		}
		if (vexRT[Btn7U])
		{
			startTask(DriveControl);
			startTask(IntakeControl);
			startTask(LiftControl);
		}
		wait1Msec(20);
	}
}
