#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorGyro)
#pragma config(Sensor, in7,    gyro,           sensorNone)
#pragma config(Sensor, dgtl1,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl3,  Claw1,          sensorDigitalOut)
#pragma config(Sensor, dgtl4,  Claw2,          sensorDigitalOut)
#pragma config(Sensor, dgtl8,  LeftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           BRD,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           MRD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ORL,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           TRL,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BRL,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           BLL,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           TLL,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           OLL,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           MLD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BLD,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include <Movement.h>
#include <Auton.h>

void pre_auton()
{

}

task autonomous()
{

}

task usercontrol()
{
	gyroCalibrate();
	SensorValue[pot] = 0;
	startTask(DriveControl);
	startTask(LiftControl);
	startTask(IntakeControl);
	//drive(1000, 40, 0.1, 0, 0); // works well
	//turn(900, 127);  // works well

	while (1)
	{
		if (vexRT[Btn8U])
		{
			while (vexRT[Btn8U]) wait1Msec(20);
			if (dumpMode == 1) startTask(hold);
			else
			{
				stopTask(hold);
				dumping();
			}
		}
	wait1Msec(20);
	}
}
